name: pba_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.*
  - pandas
  - opencv
  - matplotlib
  - scikit-learn
  - numpy
  - pip:
      - kagglehubconda env remove -n myenv

